// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpicyBot.Entities;

#nullable disable

namespace SpicyBoy.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250217045338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpicyBot.Entities.Sumo.SumoBet", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<decimal>("SumoGameId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("SumoGameId");

                    b.ToTable("SumoBets");
                });

            modelBuilder.Entity("SpicyBot.Entities.Sumo.SumoGame", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("SumoGames");
                });

            modelBuilder.Entity("SpicyBot.Entities.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("PointBalance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpicyBot.Entities.Sumo.SumoBet", b =>
                {
                    b.HasOne("SpicyBot.Entities.Sumo.SumoGame", "SumoGame")
                        .WithMany()
                        .HasForeignKey("SumoGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpicyBot.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SumoGame");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
